USE test;

DROP TABLE IF EXISTS book;

CREATE TABLE book (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(100) NOT NULL,
  ISBN VARCHAR(20) NOT NULL,
  PRINT_YEAR INT NOT NULL,
  READ_ALREADY BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (ID)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('Theoretical basis of agglomeration technologies',
        'The manual is recommended...',
        'Korotich', '5-321-00708-X', 2005);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
  VALUES ('qwer', 'lalalal', 'ivan', '3245-89', 2018);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
  VALUES ('q', 'q', 'q', '1111-11', 2017);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
  VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
  VALUES ('e', 'e', 'e', '3333-33', 2018);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
  VALUES ('r', 'r', 'r', '4444-44', 2006);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);
INSERT INTO book (TITLE, DESCRIPTION, AUTHOR, ISBN, PRINT_YEAR)
VALUES ('w', 'w', 'w', '2222-22', 2016);



/*CREATE SCHEMA 'test' DEFAULT CHARACTER SET utf8;

CREATE TABLE 'test'.'test' (
  'ID' int(11) NOT NULL AUTO_INCREMENT,
  'TITLE' varchar(255) NOT NULL,
  PRIMARY KEY ('ID'));*/

/*CREATE SCHEMA `test` DEFAULT CHARACTER SET utf8;

CREATE TABLE `test`.`user` (
  `ID` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(25) NOT NULL,
  `AGE` INT NOT NULL,
  `IS_ADMIN` BIT(1) NOT NULL DEFAULT false,
  `CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO `test`.`user` (`NAME`, `AGE`) VALUES ('Kola', '21');
INSERT INTO `test`.`user` (`NAME`, `AGE`) VALUES ('Vasa', '23');
INSERT INTO `test`.`user` (`NAME`, `AGE`) VALUES ('Dande', '56');*/